version: '3.4'
services:
  app:
    # Build at dd-trace-rb level to copy in current code
    # and use it as the `ddtrace` gem.
    build:
      context: ../../..
      dockerfile: integration/apps/ruby/Dockerfile-ci
      args:
        BASE_IMAGE: ${APP_IMAGE}
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
      - DD_AGENT_HOST=ddagent
      - DD_METRIC_AGENT_PORT=8125
      - DD_TRACE_AGENT_PORT=8126
      - DD_HEALTH_METRICS_ENABLED=true
      - DD_SERVICE=acme-ruby
      - DD_PROFILING_ENABLED=true
      # Use these to choose what is run
      - DD_DEMO_ENV_PROCESS=fibonacci
      - DD_DEMO_ENV_FEATURES=trac