version: '3.4'
services:
  app:
    build:
      context: .
      args:
        BASE_IMAGE: "datadog/dd-apm-demo:rb-${RUBY_VERSION}"
    depends_on:
      - ddagent
    environment:
      - BUNDLE_GEMFILE=/app/Gemfile
      - DD_AGENT_HOST=ddagent
      - DD_METRIC_AGENT_PORT=8125
      - DD_TRACE_AGENT_PORT=8126
      - DD_HEALTH_METRICS_ENABLED=true
      - DD_SERVICE=acme-rspec
      - DD_PROFILING_ENABLED=true
      # Use these to choose what is run
      - DD_DEMO_ENV_PROCESS=rspec
      - DD_DEMO_ENV_FEATURES=ci
      # Use this for a local version of ddtrace
      - DD_DEMO_ENV_GEM_LOCAL_DDTRACE=